#!/usr/bin/env perl
use strict; use warnings;
use lib 'lib';
use SpaceMan;
use MIME::Base64;
use Digest::SHA1;

my $man = SpaceMan->new;
my $pass = 'ajksldgjkasdlgkj';

my $ctx = Digest::SHA1->new;
$ctx->add( $pass );

my $person = $man->find_person_by_email( 'jason@nova-labs.org' );
if ( $person->verify_password( $pass ) ) {
    print "YES\n";
} else {
    print "NO\n";
}
